# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21bb3587ba82013eeb03e9640959afef3ff6783beeb79c99b66e77800b77b69e35c8d1be40e8d656ac1e9fa2bc83d90f6f5be07aafc81cb512ac690fda0ab72d

test:
  secret_key_base: 1ecca9e0ef00b658692802e9b6ca3a070c7dccbda9c24aeca48690c868c2754855efde75876a7c6d85c587152f58f126ecc7ab84a71cf80eb75271b2e58aef5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
